apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns1
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ubuntu/nginx
        ports:
        - containerPort: 80
        resources: 
          requests: 
            cpu: "100m"
        env: 
          - name: API_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: api-key 
                key: API_KEY
        volumeMounts:
          - name: secret-volume
            mountPath: /secret
      volumes: 
        - name: secret-volume
          secret: 
            secretName: api-key
