apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns1
  labels:
    app: nginx
spec:
  ports:
  - nodePort: 32104
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
